"""Programmatic EIP-7928 BAL fixtures.

These build REAL BlockAccessList objects and emit real RLP bytes + hashes,
replacing the hand-authored placeholder hashes in the initial scaffold. The
flagship is the system-contract index-confusion shape: the same (account, slot)
is written in the pre-execution (index 0), transaction (1..n), and post-execution
(n+1) phases — exactly where clients can canonicalize / index differently.

Run as a module to emit a ready-to-scan trace:

    python -m batman_detector.bal.fixtures > examples/traces/bal_system_index_confusion.generated.json
"""

from __future__ import annotations

import json

from .codec import bal_hash, encode_bal
from .model import AccountChanges, BlockAccessList, SlotChanges, StorageChange

# A representative system-contract address (e.g. an EIP-2935 / beacon-root-style
# slot target). The address value is illustrative; the *shape* is what matters.
SYS_ACCOUNT = bytes.fromhex("0000000000000000000000000000000000001000")
TARGET_SLOT = 7


def canonical_index_bal() -> BlockAccessList:
    """Spec-correct: same slot written at index 0 (pre-exec), 1 (tx), 2 (post-exec, n+1)."""
    return BlockAccessList(accounts=[
        AccountChanges(address=SYS_ACCOUNT, storage_changes=[
            SlotChanges(slot=TARGET_SLOT, changes=[
                StorageChange(0, 1),  # pre-execution system write
                StorageChange(1, 2),  # transaction write
                StorageChange(2, 3),  # post-execution system write (n+1, n=1)
            ]),
        ]),
    ])


def merged_index_bal() -> BlockAccessList:
    """A client that confuses post-exec with the tx phase: it folds the n+1 write
    onto the transaction index instead of recording a distinct index. Same final
    state value, different BAL — a concrete index-confusion divergence."""
    return BlockAccessList(accounts=[
        AccountChanges(address=SYS_ACCOUNT, storage_changes=[
            SlotChanges(slot=TARGET_SLOT, changes=[
                StorageChange(0, 1),
                StorageChange(1, 3),  # post-exec value folded onto tx index
            ]),
        ]),
    ])


def _hx(b: bytes) -> str:
    return "0x" + b.hex()


def system_index_confusion_trace() -> dict:
    """A complete, schema-valid Batman trace carrying REAL BAL bytes for two
    clients: a canonical one and an index-confusing one."""
    geth_bal = canonical_index_bal()
    reth_bal = merged_index_bal()
    geth_bytes, reth_bytes = encode_bal(geth_bal), encode_bal(reth_bal)
    slot_hex = "0x" + TARGET_SLOT.to_bytes(32, "big").hex()
    acct_hex = _hx(SYS_ACCOUNT)

    def _event(eid: str, phase: str, idx: int, note: str) -> dict:
        return {"event_id": eid, "kind": "bal_access", "phase": phase,
                "block_access_index": idx, "account": acct_hex,
                "storage_slot": slot_hex, "access_type": "write", "notes": note}

    return {
        "schema_version": "batman.trace.v1",
        "trace_id": "trace-bal-system-index-confusion-generated-001",
        "created_at": "2026-06-11T00:00:00Z",
        "target": {
            "fork": "Glamsterdam",
            "eips": ["EIP-7928"],
            "spec_refs": [{
                "name": "EIP-7928 Block-Level Access Lists",
                "url": "https://eips.ethereum.org/EIPS/eip-7928",
                "commit": "draft-as-of-2026-06-11",
            }],
        },
        "environment": {
            "topology": "single-block execution differential fixture",
            "clients": [
                {"id": "geth", "layer": "EL", "name": "geth", "version": "REPLACE", "commit": "REPLACE"},
                {"id": "reth", "layer": "EL", "name": "reth", "version": "REPLACE", "commit": "REPLACE"},
            ],
        },
        "scenario": {
            "detector_ids": ["BAL_SYSTEM_CONTRACT_INDEX_CONFUSION"],
            "description": "Generated by batman_detector.bal.fixtures. Same slot written in pre-exec/tx/post-exec phases; geth canonical vs reth folding the post-exec write onto the tx index.",
            "success_condition": "Clients disagree on BAL bytes/hash for the same minimized fixture.",
        },
        "provenance": {
            "kind": "synthetic_fixture",
            "bounty_eligible": False,
            "description": "Control fixture generated by Batman. It is not evidence of a real client bug until replaced by live client outputs.",
        },
        "block": {
            "number": 1, "slot": 1, "transaction_count": 1,
            "block_access_list_hash": _hx(bal_hash(geth_bal)),
        },
        "events": [
            _event("bal-pre-001", "pre_execution", 0, "Pre-execution system hook writes the target slot."),
            _event("bal-tx-001", "transaction", 1, "Transaction writes the same slot."),
            _event("bal-post-001", "post_execution", 2, "Post-execution system write to the same slot (n+1)."),
        ],
        "observations": [
            {"kind": "bal_output", "client_id": "geth", "payload_status": "VALID",
             "bal_rlp": _hx(geth_bytes), "bal_hash": _hx(bal_hash(geth_bal)),
             "notes": "Canonical BAL: distinct indices 0/1/2 for the same slot."},
            {"kind": "bal_output", "client_id": "reth", "payload_status": "VALID",
             "bal_rlp": _hx(reth_bytes), "bal_hash": _hx(bal_hash(reth_bal)),
             "notes": "Index-confusion BAL: post-exec write folded onto the tx index."},
        ],
    }


if __name__ == "__main__":
    print(json.dumps(system_index_confusion_trace(), indent=2))
